### ISSUE TITLE
Объекты встроенного кода Python

### ISSUE THREAD

**Issue by GDVFox** [bmstu-iu9/utp2018-4-spreadsheet#12]
Когда-нибудь)))))))

**Comment by AleksMa** [comment]
Ты дурак??????

**Comment by AleksMa** [comment]
Мы кончили

**Comment by AleksMa** [comment]
Соре

**Comment by Mazdaywik** [comment]
Раз уж вы пишете на JavaScript, то разумнее сделать встроенный код (наверное, речь о макросах) на самом JavaScript. И вызывать его через `eval`.

**Comment by GDVFox** [comment]
> Раз уж вы пишете на JavaScript, то разумнее сделать встроенный код (наверное, речь о макросах) на самом JavaScript. И вызывать его через eval.

Здесь речь о очень далёкой и призначной надежде получить из наших табличек интрумент для удобной подготовки/обработки/очищения данных для задач ML, поэтому Python будет более уместным. Но это скорее всего не будет реализовано к финалу.

**Comment by Mazdaywik** [comment]
ML — это что?

**Comment by GDVFox** [comment]
ML - Machine Learning(Машинное обучение)
Вот из наших таблиц может получится инструмен для подготовки данных(пункт 2)
 
![image](https://user-images.githubusercontent.com/19743266/42515848-6585f5aa-8465-11e8-82f4-2bcb7a3fb4a1.png)

**Comment by Mazdaywik** [comment]
А то ML — это и [семейство языков программирования](https://ru.wikipedia.org/wiki/ML), и markup language.
