### ISSUE TITLE
Бесконечная таблица: front

### ISSUE THREAD

**Issue by GDVFox** [bmstu-iu9/utp2018-4-spreadsheet#2]
Сделать бесконечную таблицу.
**Способ расширения**: когда до края остаётся ~5 столбцов/строк генерируем и вставляем новые 5
**Необходимый функционал**:
* Редактирование содержимого ячеек (договориться с @Apakhov о передаче формул)
* Изменение размера столбца/строки
* Заливка фона
* Подготовить возможность для работы с содержимым (менять font, size и т.д)

Пока так

**Comment by Apakhov** [comment]
done
