### ISSUE TITLE
Запуск

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-4-spreadsheet#35]
Не получается запустить приложение по указанной инструкции.
Использовался Windows 7.

**Comment by GDVFox** [comment]
Использование файлов с расширением .sh для автоматического запуска всех серверов предполагает UNIX систему.
Для запуска серверов на Windows(зачем-то) нужно зайти в каждую папку{save_service, auth_service} и выполнить: `node <имя_папки>.js`, а затем `node app.js` в корне проекта.

И всё же рекомендую использовать Linux для наших серверов.

**Comment by Mazdaywik** [comment]
Проблема решается просто. Добавьте синхронные `.bat`-файлы, потому что я тоже буду запускать на Windows.

**Comment by Mazdaywik** [comment]
Собственно, я так и делаю:

https://github.com/bmstu-iu9/simple-refal

Полазьте в папках, посмотрите на пары скриптов.
